version: 1.0.1
destination: _site
source: .
exclude: [grunt, node_modules, test,
          app.rb,config.ru,
          analytics.iml,
          circle.yml, Gemfile, Gemfile.lock, package.json,rakefile, Gruntfile.js]
port: 4000