version: 1.3.2rc1
destination: _site
source: .
exclude: [grunt, node_modules, test,
          app.rb,config.ru,
          analytics.iml,
          circle.yml, Gemfile, Gemfile.lock, package.json,rakefile, Gruntfile.js]
include: [_includes]
port: 4001
